jupyter-widgets/pythreejs

examples/Examples.ipynb, pythreejs/pythreejs.py
@jasongrout this fixes the imports for IPython 4.0dev.  With the second part of the Big Split, `jupyter_notebook.widgets` is gone and replaced with `ipython_widgets`
Besides, there is a shim for the old import path `IPython.html.widgets`.
=> Fix IPython widget imports

pythreejs/nbextension/pythreejs.js
Currently, pythreejs adds some paths in requirejs' config.
The problem is that the target paths start with `/` witch removes the url prefix and makes pythreejs incompatible with any app that embeds the notebook with a URL prefix such as binder. (@jasongrout, the flight-simulator binder uses a patched version of pythreejs).
Because of https://github.com/jupyter/notebook/issues/626, we cannot simply remove the slashes, and it does not seem that this issue will be fixed 
In this PR, I completely remove the use of requirejs paths, to the benefit of maps. It is a bit longer but should work in all situations.
=> Dont use requirejs path

examples/Examples.ipynb, pythreejs/nbextension/pythreejs.js, pythreejs/pythreejs.py, setup.py
This PR contains the required changes to make pythreejs compatible with the current (backward incompatible) development version of ipywidgets.
- Add a custom js side model for each pythreejs widget, providing default values on the js side for each widget attribute.
- Remove the Color trait type defined in pythreejs, and now use the one defined in ipywidgets.
- Use the new traitlets API.
=> Ipywidgets5 compat

js/src/jupyter-threejs.js
The `jupyter-widgets` class causes some top el margins to be set accordingly to the rest of ipywidgets...
=> Add semantic class

pythreejs/__init__.py, pythreejs/_package.py, pythreejs/pythreejs.py
This is the start of some clean-up/organization I'd like to do within the codebase.  I think the project could benefit greatly by mirroring the hierarchy of the three.js code base.  
Anyways, this is just a tiny little PR to gauge whether you're welcoming to contribution or not.  My plan is to split the python libraries out into separate files corresponding to the different sections of the three.js docs:
- cameras
- extras
- materials
- objects
- renderers
- scenes
- textures
etc. ...
The result would be that `__init__.py` imports vars from a number of files as opposed to a single python file. 
I'm curious what you think, and if you're open to me working on some clean-up/organization.  Thanks!
=> create _package.py for storing package name info

pythreejs/enums.py, pythreejs/pythreejs.py
@jasongrout @SylvainCorlay 
Isolating this change from other pull requests to ease reviewing.  
Store enum string names in named arrays for easy referencing in py trait constructors.
=> Refactor enums to store enum strings in named arrays

MANIFEST.in, js/package.json, js/src/jupyter-threejs.js, js/webpack.config.js, jslab/package.json, pythreejs/_version.py, setup.py, setupbase.py
Also updates version to 0.4.0
CC @vidartf
=> WIP upgrade to ipywidgets 7

examples/Shadows.ipynb, js/scripts/generate-wrappers.js, js/scripts/prop-types.js, js/scripts/templates/py_wrapper.mustache, js/scripts/three-class-config.js, js/src/_base/Renderable.js, js/src/_base/RendererPool.js, js/src/_base/Three.js, js/src/_base/utils.js, js/src/cameras/OrthographicCamera.js, js/src/cameras/PerspectiveCamera.js, js/src/core/Renderer.js, js/src/lights/LightShadow.js, js/src/materials/Material.js, js/src/objects/CloneArray.js, js/src/renderers/WebGLRenderer.js, js/src/renderers/webgl/WebGLShadowMap.js, js/src/textures/TextTexture.js, pythreejs/_base/Three.py, pythreejs/_base/renderable.py, pythreejs/core/Renderer.py, pythreejs/materials/Material.py, pythreejs/renderers/WebGLRenderer.py, pythreejs/traits.py
Fixes #84. Fixes #81.
Also enables rendering configs on all renderers, including antialiasing (changing this requires a new webgl context, so the renderer pool had to be updated to support this).
=> Enable shadows, antialias and other renderer config

.gitignore, .travis.yml, README.md, examples/Animation.ipynb, js/scripts/generate-wrappers.js, js/scripts/templates/py_wrapper.mustache, pytest.ini, pythreejs/core/Renderer.py, setup.py
Adds some basic travis CI:
- Uses [nbval](https://github.com/computationalmodelling/nbval) to check that the example notebooks run without errors (they currently do not). It is also set up to generate a coverage report based on the examples, but this can be removed if not wanted.
- Uses [pytest-check-links](https://github.com/minrk/pytest-check-links) to check links in example notebooks and HTML/markdown files. One nitpick was found and fixed.
Based on #83 for improved setup.
=> Add some basic CI checks of examples and links

js/src/objects/Blackbox.js
The autogenerated BlackBoxModel creates a `new THREE.Blackbox()` which doesn't exist.
This override creates an Object3D instead.
Note that I still have problems getting my blackbox subclass to actually render, getting `this.parent === undefined` at the last line here in `Object3D`:
```
updateMatrixWorld: function ( force ) {
if ( this.matrixAutoUpdate ) this.updateMatrix();
if ( this.matrixWorldNeedsUpdate || force ) {
if ( this.parent === null ) {
this.matrixWorld.copy( this.matrix );
} else {
this.matrixWorld.multiplyMatrices( this.parent.matrixWorld, this.matrix );
```
I haven't been able to find any place where this.parent is actually set to undefined, it's initialized to null everywhere I've seen.
=> Bugfix: make BlackboxModel create an Object3D instead of Blackbox

js/scripts/prop-types.js, js/scripts/three-class-config.js, js/src/_base/Three.js, js/src/animation/AnimationAction.js
- Fix animation faulty rerender trigger signature.
- Fix assignment of dicts to undefined/null values on three object.
- Allow Mesh.material to be either one material or an array of materials.
=> Various fixes and adjustments

README.md
For me it wasn't obvious I need to be in the `./js/` dir for the `npm` commands. Otherwise you get an error about a missing `package.json`.
Also I had to change `build` to `build:all` (or any of the other scripts defined `package.json`).
=> Update autogen related commands in the README

examples/Animation.ipynb, examples/Geometries.ipynb, examples/Textures.ipynb, examples/conftest.py, js/scripts/generate-wrappers.js, js/scripts/three-class-config.js, pythreejs/core/BufferGeometry.py, setup.py
- Fixes default value for `types` attribute of many widgets with some special logic in autogen code.
- Make BufferGeometry repr shorter. For big arrays you cannot see the entire array anyway.
- Regenerate examples with embedded state.
=> Ensure examples pass non-lax nbval test

js/src/_base/RendererPool.js
There were a few minor bugs in the `KeyedCollection` and the `acquire` function causing `freePool` not to be used and `this.numCreated` exceeding `MAX_RENDERERS` after a few displays.
=> fix widgets disappearing after several displays of a renderer

pythreejs/traits.py
The base class warns about 64-bit ints in the serializer, which is mostly a source of noice. Here, we try to be smarter about it by casting on validation, and only giving a warning if the original source was another ndarray.
Closes #164.
=> Coerce 64-bit ints as well as floats

js/src/_base/Renderable.js
Still allow it on the non-renderer area of the widget view.
=> Prevent context menu on renderers

examples/Examples.ipynb, js/scripts/prop-types.js, js/scripts/templates/py_wrapper.mustache
- Use `TypedTuple` from ipywidgets, allowing for variable length, while still performing type check.
- Lint some long lines.
Closes #212.
=> Use TypedTuple instead of Tuple 

js/scripts/prop-types.js
Previously, the defaults for autogenerated JS that are +/-Infinity would be incorrectly emitted as null.
Fixes #215.
=> Correctly generate infinity defaults in JS

js/scripts/generate-shader-utils.js, js/scripts/generate-wrappers.js, js/scripts/prop-types.js, js/scripts/templates/js_wrapper.mustache, js/scripts/templates/py_wrapper.mustache, js/src/_base/Preview.js, js/src/_base/Renderable.js, js/src/_base/Three.js, js/src/_base/serializers.js, js/src/core/Renderer.js, js/src/renderers/WebGLRenderer.js, pythreejs/_base/uniforms.py, pythreejs/core/Renderer.py, pythreejs/pythreejs.py, pythreejs/traits.py
- Fixes some issues after #196.
- Adds serializers for uniforms (replaces converter), that also adds support for all valid uniform types (including textures). CC @safijari.
- Adds own color trait until we can rely on https://github.com/jupyter-widgets/ipywidgets/pull/2222
- Adds trait validation for uniforms.
=> Fix serializers and uniforms

js/src/_base/Three.js
Add a special change callback for when the data in a data widget change. This will not trigger the normal change notifier, which would normally push this to the three object. Note that since this attribute will not be be marked in `hasChange()`. For this reason, either property mapper should be used, or this callback should call `syncToThreeObj` with `force=true`. For now, we rely on mappers.
=> Fix listen to datawidget

examples/Picker.ipynb
Add a `Picker` example with a more engaging use case, highlighting better:
- That a picker can be used as input for calculation on the kernel.
- Explaining the picker logic step-by-step.
- Showing how to add controls to an existing renderer.
- Showing how to live-plot a line object (re-render per iteration).
=> Add a more extensive picker example

pythreejs/traits.py
I assumed creating a global CFLOAT variable was ok? If not I'll change to the `Undefined` mecanism used for the `default_value` argument.
=> Replaces CFloat class by CFloat() instances in __init__ methods #236

examples/Capture.ipynb, js/package.json, js/src/_base/Renderable.js, setup.py
Several PRs were also opened to ipywebrtc to improve the experience.
Closes #22.
Closes #106.
Closes #167.
=> Add ipywebrtc captureStream interface

js/scripts/.eslintrc.js, js/scripts/generate-enums.js, js/scripts/generate-shader-utils.js, js/scripts/generate-wrappers.js, js/scripts/post-build.js
Just makes the autogen scripts easier to reason about.
=> Use async in scripts

js/scripts/prop-types.js, js/scripts/three-class-config.js
=> Fix faceVertexUvs default

pythreejs/traits.py
Silence deprecation warning from collections.
```
\site-packages\pythreejs\traits.py:4
C:\Users\genevieb\AppData\Local\conda\conda\envs\ipyvolume-dev\lib\site-packages\pythreejs\traits.py:4: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
from collections import namedtuple, Sequence
```
=> Update traits.py for collections deprecation warning

pythreejs/pythreejs.py
Here's a one line fix to silence a traitlets deprecation warning in pythreejs.py
Similar to issue https://github.com/jupyter-widgets/pythreejs/issues/236
Traitlets warning encountered:
```
...\site-packages\pythreejs\pythreejs.py:56
C:\Users\genevieb\AppData\Local\conda\conda\envs\ipyvolume-dev\lib\site-packages\pythreejs\pythreejs.py:56: DeprecationWarning: Traits should be given as instances, not types (for example, `Int()`, not `Int`). Passing types is deprecated in traitlets 4.1.
z = List(CFloat, [0] * 100)
-- Docs: https://docs.pytest.org/en/latest/warnings.html
```
=> Update pythreejs.py to silence traitlets warning

js/src/jupyterlab-plugin.js
This lazy-loads the main widgets (and therefore THREE) in lab with [require.ensure](https://webpack.js.org/api/module-methods/#requireensure). This cuts ~6mb off a dev `vendors~main`, and 1.1mb off a prod one, ignoring the sourcemap changes.
=> Lazy-load widgets in jupyterlab

docs/environment.yml, docs/source/conf.py, setup.py
This is not necessary anymore since `nbsphinx` automatically supports widgets (see https://github.com/spatialaudio/nbsphinx/pull/345).
Closes #275.
=> DOC: Remove jupyter_sphinx

.travis.yml
As speculated in https://github.com/jupyter-widgets/pythreejs/pull/307#issuecomment-569780225, it turns out that the `GROUP=docs` tests have never been running on Travis-CI.
And they are of course totally not passing.
=> Travis-CI: Change YAML escaping

.travis.yml, setup.py
... but don't worry, there are still plenty left!
=> Fix a few Travis errors

.travis.yml, docs/sphinxext/autodoc_traits.py, pythreejs/traits.py
Fixes #334 .
Traitlets 5 changed how `self.default_value` was used vs the dynamic default callback of the `Instance` trait type (in v5 `default_value` takes precedence over the dynamic default). ~This avoids us writing to that value, as I don't think we every rely on it.~ Here we ensure that the value we write is correct, so that ipywidgets sync logic is correct.
=> fix traitlets5 compat

.github/workflows/ci.yml, .gitignore, docs/source/conf.py, js/scripts/templates/py_enums.mustache, pyproject.toml, pythreejs/_version.py, pythreejs/enums.py, setup.py
This adds a GitHub Actions CI, derived from a number of other ones in the community. This is a single workflow, with one _tiny_ change to `conf.py` to avoid a long-deprecated API. I figure we can remove the travis job separately, maybe try to get RTD back up and running (might need to request the mamba feature flag).
I'm working directly off my `master` branch, where you can see my [Many Commits of Shame](https://github.com/bollwyvl/pythreejs/actions?query=workflow%3ACI+branch%3Amaster) with the occasional :heavy_check_mark: 
Overview:
- linux build job
- uploads distribution artifacts
- linux docs job
- uploads docs artifacts
- checks all links
- :new: uses a link cache, expires every week
- matrix test job (3 os x 4 pythons x 3 labs x 2 LTS nodejs)
- downloads the distribution artifacts …
=> add github actions

js/scripts/three-class-config.js, js/src/controls/Picker.js
This adds on parameters to the `Picker` object so that the pick-threshold for points and lines can be adjusted, and so that it will return the `instanceId` of an instanced mesh as well as the `index` when picking on a `Points` object.  This enables the `Picker` object to work with `Points` and `PointClouds`, where it returns the index into a `BufferGeometry` corresponding to the picked (sub)instance.
I believe this is relevant to #333, as it should enable indexing into a `BufferGeometry` and the corresponding attributes to retrieve the color (or other attributes of the source array).
=> Extend Picker to pick individual Points objects.
