jupyter-widgets/pythreejs

.gitignore, js/package.json, js/src/jupyter-threejs.js, js/src/labplugin.js, js/webpack.config.js, pythreejs/__init__.py
=> Jupyterlab extension

pythreejs/pythreejs.py
As the title states, should be simple to accept. This is my first PR so please let me know what needs to happen (if anything) in order to get this accepted.
=> Fixed typo in Renderer and removed unused import

js/src/jupyter-threejs.js
Also, make the base 3d object update parameters that it initializes.
=> Make lights inherit from the base 3d object

js/src/_base/Preview.js
Also changed default material from MeshStandardMaterial to
MeshLambertMaterial (some objects were just flat looking).
This may change the default visual impression when displaying objects, feel free to review and adjust.
=> Automatically adjust camera to include whole scene in preview widget.

LICENSE, js/package.json, setup.py, setupbase.py
I had some problems installing from source (on Windows), so I updated the setup code to use [jupyter-packaging](https://github.com/jupyter/jupyter-packaging).
=> Use setupbase from jupyter-packaging

js/scripts/three-class-config.js, js/src/_base/Preview.js, js/src/controls/FlyControls.js, js/src/core/Renderer.js, js/src/examples/controls/MomentumCameraControls.js
FlyControls were broken in #88. This fixes it again (and also includes another minor bug).
=> Fix FlyControls

js/src/controls/TrackballControls.js, js/src/examples/controls/TrackballControls.js
The trackball controls were broken after #88. This PR should fix them again.
=> Fix trackball controls

js/src/_base/RendererPool.js
=> Fix renderer pixel ratio

setup.py
=> Add numpy dependency

js/package.json, js/scripts/three-class-config.js
Also update some other web dependencies to the latest version.
=> Update threejs to r88

jupyter-config/notebook.d/jupyter-threejs.json, setup.py, setupbase.py
Gives automatic enabling of nbextension for notebook >= 5.3 as long as package is installed in notebook env.
=>  Add configuration dir data files 

pythreejs/pythreejs.py
=> Fix surfacegrid divide by zero error

docs/source/introduction.rst, js/scripts/generate-wrappers.js, js/scripts/prop-types.js, js/scripts/templates/autodoc.mustache, js/scripts/three-class-config.js
Adds option to add help option on props, then uses this to document the Picker.
Closes #29.
=> Document picker

js/scripts/three-class-config.js
=> Allow exponential fall-off fog in scene

js/src/_base/Three.js
=> Convert funcs of nullable prop types handle null

docs/source/examples/Renderer.nblink, examples/Renderer.ipynb, js/src/_base/Renderable.js, js/src/core/Renderer.js, pythreejs/_base/renderable.py, pythreejs/core/Renderer.py, pythreejs/renderers/WebGLRenderer.py
Ensure a transparent background can be used for renderers, and add an example notebook demonstrating the effect of renderer clear color/opacity + scene background color.
=> Renderer background

js/package-lock.json, js/package.json, js/src/textures/ImageTexture.js, setup.py
Should be resolved relative to notebook location. Use util on widgets to ensure we get the correct location.
Fixes #165.
=> Ensure we resolve any local texture URLs

docs/source/extending.rst, examples/Examples.ipynb
=> Have examples notebook use scale for resizing ball

pythreejs/controls/OrbitControls.py
=> Expose the reset method on OrbitController

js/src/animation/AnimationAction.js, pythreejs/animation/AnimationAction.py
Add kernel-side controls for AnimationAction.
Closes #190.
=> Add kernel interface for play/pause/stop

js/package.json
=> Add mkdirp as a dev dependency

js/scripts/generate-wrappers.js, js/scripts/templates/py_wrapper.mustache, js/scripts/three-class-config.js
=> Raise an error if instantiating unimplemented objs

js/src/controls/OrbitControls.js, js/src/controls/TrackballControls.js, js/webpack.config.js
=> Push updated target from controls

js/src/controls/OrbitControls.js, js/src/controls/TrackballControls.js
=> Fix update of controller target

js/package.json, js/scripts/three-class-config.js
While it isn't currently clear from the threejs documentation, the [source code](https://github.com/mrdoob/three.js/blob/ce501ae22b51665646a8d4a8a7131d78cc54005f/src/core/BufferAttribute.js#L23) is pretty clear.
=> The normalized attribute of BufferAttribute should default to false

examples/Animation.ipynb, examples/Examples.ipynb, js/package-lock.json, js/package.json, js/scripts/generate-wrappers.js, js/scripts/three-class-config.js, js/scripts/three-enum-config.js, js/src/_base/Preview.js, js/src/_base/enums.js, js/src/examples/controls/MomentumCameraControls.js, js/src/examples/controls/OrbitControls.js, js/src/examples/controls/TrackballControls.js, js/src/textures/DataTexture3D.js, pythreejs/enums.py, pythreejs/textures/DataTexture3D.py
See three.js changelogs from r89 to r97 to see the changes. Note: The controls have not all been update fully. Especially, the default panning mode of the OrbitControls are kept as they were.
=> Update three.js to r97

js/scripts/generate-wrappers.js, js/scripts/prop-types.js, js/scripts/templates/js_wrapper.mustache, js/src/_base/Preview.js, js/src/_base/Renderable.js, js/src/_base/Three.js, js/src/core/Renderer.js, js/src/renderers/WebGLRenderer.js
Ensure three object is created before we return a deserialized reference to the model.
Fixes #195.
=> [WIP] Add own widget deserializer

js/scripts/three-class-config.js, js/src/_base/Three.js, js/src/_base/utils.js, js/src/core/InstancedBufferGeometry.js, js/src/core/InstancedInterleavedBuffer.js, js/src/core/InterleavedBuffer.js, js/src/objects/CloneArray.js, pythreejs/core/BufferGeometry.py
- Fix instanced/interleaved buffers.
- Add custom classes in constructor LUT, so they can be initialized from the JS side.
=> Various fixes

js/src/jupyterlab-plugin.js, js/src/version.js
=> Fix lab registered version

examples/Animation.ipynb, examples/Geometries.ipynb, js/package-lock.json, js/scripts/generate-wrappers.js, js/scripts/templates/js_wrapper.mustache, js/scripts/templates/py_wrapper.mustache, js/scripts/three-class-config.js, js/src/geometries/EdgesGeometry.js, pythreejs/sage.py
Also includes some other minor tweaks.
Fixes #252.
Fixes #251.
=>  Add EdgesGeometry definition

js/scripts/three-class-config.js, js/src/helpers/ArrowHelper.js
=> Fix ArrowHelper

js/src/_base/utils.js
Fixes #276.
Not sure of the source of that term, but it definitely does not belong there :)
=> Fix computeBoundingSphere

README.md
=> Improved extension install instructions for lab vs. notebook

js/src/_base/Renderable.js, js/src/_base/RendererPool.js, pythreejs/_base/renderable.py, pythreejs/core/Renderer.py, pythreejs/renderers/WebGLRenderer.py
Fixes https://github.com/jupyter-widgets/pythreejs/issues/244.
=> Support and default to webgl2

js/src/core/Renderer.js, pythreejs/core/Renderer.py
=> Hold auto--rerender context manager

js/src/_base/Three.js
Fixes https://github.com/jupyter-widgets/pythreejs/issues/284.
=> Ensure we dispose wrapped objects when widget is destroyed

.travis.yml, docs/source/introduction.rst, examples/BufferAttributes and BufferGeometry.ipynb, examples/Examples.ipynb, examples/Geometries.ipynb, examples/GeometryVertices.ipynb, examples/Textures.ipynb, examples/conftest.py, examples/renderer_limit.ipynb, examples/superellipsoid.ipynb, examples/test.ipynb, examples/threejs/voxel_painter.ipynb
=> fix docs ci

js/.npmignore, js/scripts/generate-wrappers.js, js/webpack.config.js
cc @bollwyvl 
cf https://github.com/jupyter-widgets/pythreejs/pull/353#discussion_r581514473
Note that since this project doesn't transpile the JS, the `src` folder is pretty critical to include. It could probably be called `lib` directly, but whatever.
=> Clean up the npm pack
